name: ristocmd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.3
  http: ^1.1.0
  badges: ^3.1.2  
  provider: ^6.0.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  shimmer: ^2.0.0
  socket_io_client: ^1.0.1 
  device_info_plus: ^10.0.1
  reorderables: ^0.4.2
  # flutter_local_notifications: ^9.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true