name: ristocmd
description:   Un'app intelligente per la gestione dei tavoli di un ristorante, che consente al personale di visualizzare, gestire e aggiornare tavoli, ordini e coperti, anche in modalità offline."
publish_to: 'none'

version: 2.1.3+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.3
  http: ^1.1.0
  badges: ^3.1.2  
  provider: ^6.0.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  shimmer: ^2.0.0
  socket_io_client: ^1.0.1
  device_info_plus: ^10.0.1
  reorderables: ^0.4.2
  flutter_dash: ^1.0.0
  flutter_local_notifications: ^16.3.2 
  permission_handler: ^11.0.1
  google_fonts: ^6.2.1
  lottie: ^2.7.0
  android_intent_plus: ^5.0.2
  disable_battery_optimization: ^1.1.1
  package_info_plus: ^8.3.0
  vibration: ^2.0.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets: 
    - images/ristocmd/
    - animations/ristocmd/
